### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by crypt0inf0** [JChris246/youtube_rss#1]
I got the following error,

```
$ curl localhost:8080/api/channels/UCXuqSBlHAE6Xw-yeJA0Tunw
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/channels/UCXuqSBlHAE6Xw-yeJA0Tunw</pre>
</body>
</html>
```

`UCXuqSBlHAE6Xw-yeJA0Tunw` is the channel ID

**Comment by JChris246** [comment]
My bad for not having a readme. What exactly were you trying to get by hitting that route?

**Comment by crypt0inf0** [comment]
I'm trying to get the latest post from the youtube channel once it's been uploaded. Like a rss stream.

**Comment by JChris246** [comment]
Hit the `/api/videos/:id` endpoint (e.g. curl localhost:8080/api/videos/UCXuqSBlHAE6Xw-yeJA0Tunw) and the first item in the returned array will be the latest video from that channel

https://github.com/JChris246/youtube_rss#get-latest-videos-from-a-channel

**Comment by crypt0inf0** [comment]
Thanks
